### ISSUE TITLE
WorldLimit doesn't deactivate fly when it should

### ISSUE THREAD

**Issue by Broascaa** [Zrips/CMI-API#42]
Player's fly is not disabled when they enter another world while they have fly active. I'm only using CMI as fly plugin and i'm using FlightCharge as a "TempFly" plugin.
players do not have access to `/fly` or `/flyc`

```YML
WorldLimits:
  Enabled: true
  Fly:
  - world_iris:false
  - world_nether:false
  - world_the_end:false
  - world_spawn:false
  - world_pvp:false
  - world_dungeon:false
  - world_pinata:false
  - world_denied_resourcepack:false
  - parkour_whirlpool:false
  - parkour_biomes:false
  - event_parkour:false
  - event_labirinth:false
```
