### ISSUE TITLE
Conflict with TNE resulting in crashes with 10 or more players online

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI-API#7]
**Description of issue or feature request:**
When CMI and TNE are both present (using TNE version 0.1.1.7) the server begins to error and then crashes whenever 10 or more players login or one of a smaller number of players spams logins and outs.  If either TNE or CMI is removed, the errors disappear and the crashes no longer occur. 
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/5KnpuMUF
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  Enabled: false
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Determines max amount of cheque player can create
  # Set it to 0 to remove limit
  MaxChequeValue: 1.0E8
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    - nation-
    - nation_
  Global:
    # Starting amount of money players will have
    StartingAmount: 200.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 1.0E8
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: $
    # Placing of currency symbol
    Placing: '[symbol][money]'
```

---

**Cmi Version (using`/cmi version`):** 
8.2.8.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot version 1.13.2 (but also occurs in 1.13.1)

**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
